import {
  ArrowLeftRight,
  ArrowRightFromLine,
  ArrowRightLeft,
  GitBranch,
  RefreshCw,
  RotateCw,
  Square,
} from "lucide-react";
import type { FeatureConfig } from "./feature-config";

export const dataStructures: FeatureConfig[] = [
  {
    id: "singly-linked-list",
    title: "Singly Linked List",
    description: "A linear data structure where each node points to the next.",
    path: "data-structures/singly-linked-list",
    status: "active",
    icon: ArrowRightFromLine,
    type: "Data Structures",
    tags: ["linked list", "singly linked list", "data structure", "sll"],
    features: ["Insert", "Delete", "Traverse"],
  },
  {
    id: "doubly-linked-list",
    title: "Doubly Linked List",
    description: "Each node holds pointers to both next and previous nodes.",
    path: "data-structures/doubly-linked-list",
    status: "active",
    icon: ArrowLeftRight,
    type: "Data Structures",
    tags: ["linked list", "doubly linked list", "data structure", "dll"],
    features: ["Insert", "Delete", "Reverse Traverse"],
  },
  {
    id: "circular-linked-list",
    title: "Circular Linked List",
    description: "The tail node links back to the head, forming a cycle.",
    path: "data-structures/circular-linked-list",
    status: "active",
    icon: RotateCw,
    type: "Data Structures",
    tags: ["linked list", "circular linked list", "data structure", "cll"],
    features: ["Insert", "Delete", "Cycle Detection"],
  },
  {
    id: "stack",
    title: "Stack",
    description:
      "Last-in, first-out structure. Used in undo, parsing, and DFS.",
    path: "data-structures/stack",
    status: "active",
    icon: Square,
    type: "Data Structures",
    tags: ["stack", "data structure", "lifo", "last in first out"],
    features: ["Push", "Pop", "Peek"],
  },
  {
    id: "linear-queue",
    title: "Queue",
    description: "First-in, first-out structure. Used in scheduling and BFS.",
    path: "data-structures/queue/linear",
    status: "active",
    icon: GitBranch,
    type: "Data Structures",
    tags: ["queue", "data structure", "fifo", "first in first out"],
    features: ["Enqueue", "Dequeue", "Peek"],
  },
  {
    id: "circular-queue",
    title: "Circular Queue",
    description: "A queue where the tail wraps around to reuse freed space.",
    path: "data-structures/queue/circular",
    status: "active",
    icon: RefreshCw,
    type: "Data Structures",
    tags: ["circular queue", "data structure", "circular fifo"],
    features: ["Enqueue", "Dequeue", "Wrap-around"],
  },
  {
    id: "deque",
    title: "Deque",
    description: "A double-ended queue — insert and remove from both ends.",
    path: "data-structures/queue/deque",
    status: "active",
    icon: ArrowRightLeft,
    type: "Data Structures",
    tags: ["deque", "double-ended queue", "data structure"],
    features: ["Push Front", "Push Back", "Pop Front", "Pop Back"],
  },
];
